# Generated by Django 3.1.4 on 2021-03-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ManyToManyField(to='rest_app.Language')),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.paradigms'),
        ),
    ]
